name: Deploy Strapi
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-deploy:
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm install -g yarn
      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
      - name: Deploy to server
        env:
          HOST: '${{ secrets.HOST }}'
          USERNAME: '${{ secrets.USERNAME }}'
          SSH_PRIVATE_KEY: '${{ secrets.SSH_PRIVATE_KEY }}'
          ENV_VARS: '${{ secrets.ENV_VARS }}'
        run: >
          ssh -i key.pem -o StrictHostKeyChecking=no
          ${SERVER_USER}@${SERVER_HOST} "
            cd ~/strapi &&
            git pull origin master &&
            npm install &&
            npm run build &&
            nohup npm start &
          "
