# This is a CI/CD workflow for deploying a Strapi application

name: CI/CD for Strapi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.SERVER_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy Strapi Application
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_KEY: ${{ secrets.SERVER_KEY }}
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_HOST} "
            cd ~/strapi &&
            git pull origin master &&
            npm install &&
            npm run build &&
            nohup npm start &
          "
